"""empty message

Revision ID: 1b2d237542a8
Revises: 7cb78be96aee
Create Date: 2016-02-05 03:54:42.632062

"""

# revision identifiers, used by Alembic.
revision = '1b2d237542a8'
down_revision = '7cb78be96aee'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(length=80),
               type_=sa.String(length=60),
               existing_nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=sa.String(length=60),
               type_=mysql.VARCHAR(length=80),
               existing_nullable=True)
    ### end Alembic commands ###
